const TOKEN = process.env.TOKEN;
const GUILD_ID = process.env.GUILD_ID || '';
const STAFF_CHANNEL = process.env.STAFF_CHANNEL || '';
const CLASSIFICA_CHANNEL = process.env.CLASSIFICA_CHANNEL || '';
const CATEGORY_ID = process.env.CATEGORY_ID || '';
const STORICO_CHANNEL = process.env.STORICO_CHANNEL || '';
const TOURNAMENT_FULL_CHANNEL = process.env.TOURNAMENT_FULL_CHANNEL || STAFF_CHANNEL;
const REGISTRATION_STATUS_CHANNEL = process.env.REGISTRATION_STATUS_CHANNEL || '';

module.exports = {
  TOKEN,
  GUILD_ID,
  STAFF_CHANNEL,
  CLASSIFICA_CHANNEL,
  CATEGORY_ID,
  STORICO_CHANNEL,
  TOURNAMENT_FULL_CHANNEL,
  REGISTRATION_STATUS_CHANNEL
};
